name: Empty Commit on Main

on:
  push:
    branches:
      - main
      - Prince-captcha
      - krish-chat
      - kinjal-test
      - master
      - seo
      - seo-test

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last commit message
        id: get_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Create empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "deploy: ${{ steps.get_message.outputs.message }}"
          git push
